[2015-10-09 16:30:03] request.INFO: Matched route "ex4read_confirmarRegistro" (parameters: "_controller": "Libreame\BackendBundle\Controller\RegistroController::confirmarRegistroAction", "id": "ng0122024blakisiimcaisoasn@dgmeakilk.ucosmchrlm5h0fsywf1ctp8p-t*7-untudtstmq~z-3sst7*7fr~r3xmbde6gbik1lx2o7tl6vzf3higev0*kyeyicojr89q75xse7sla~ngblq0hlpd8", "_route": "ex4read_confirmarRegistro") [] []
[2015-10-09 16:30:03] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\DBALException: "An exception occurred while executing 'INSERT INTO lb_actsesion (inActAccion, txActMensaje, feActFecha, inActFinalizada, inActSesionDisUs) VALUES (?, ?, ?, ?, ?)' with params ["6", "Registro confirmado para usuario baisicasas@gmail.com", "2015-10-09 16:30:03", 1, 74]: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'txActMensaje' at row 1" at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\dbal\lib\Doctrine\DBAL\DBALException.php line 91 {"exception":"[object] (Doctrine\\DBAL\\DBALException: An exception occurred while executing 'INSERT INTO lb_actsesion (inActAccion, txActMensaje, feActFecha, inActFinalizada, inActSesionDisUs) VALUES (?, ?, ?, ?, ?)' with params [\"6\", \"Registro confirmado para usuario baisicasas@gmail.com\", \"2015-10-09 16:30:03\", 1, 74]:\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'txActMensaje' at row 1 at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\DBALException.php:91, PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'txActMensaje' at row 1 at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Statement.php:165)"} []
[2015-10-09 16:32:59] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /registro/ng0122024blakisiimcaisoasn@dgmeakilk.ucosmchrlm5h0fsywf1ctp8p-t*7-untudtstmq~z-3sst7*7fr~r3xmbde6gbik1lx2o7tl6vzf3higev0*kyeyicojr89q75xse7sla~ngblq0hlpd8"" at C:\xampp\htdocs\Ex4ReadBE\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 145 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /registro/ng0122024blakisiimcaisoasn@dgmeakilk.ucosmchrlm5h0fsywf1ctp8p-t*7-untudtstmq~z-3sst7*7fr~r3xmbde6gbik1lx2o7tl6vzf3higev0*kyeyicojr89q75xse7sla~ngblq0hlpd8\" at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:145, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\Ex4ReadBE\\app\\cache\\prod\\appProdUrlMatcher.php:52)"} []
[2015-10-13 14:45:27] request.INFO: Matched route "ex4read_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "ex4read_ingresarSistema") [] []
[2015-10-13 14:45:28] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\DBALException: "An exception occurred while executing 'INSERT INTO lb_usuarios (txUsuEmail, txUsuTelefono, txUsuNombre, inUsuGenero, txUsuImagen, txUsuNomMostrar, feUsuNacimiento, txUsuValidacion, inUsuEstado, txUsuClave, inUsuLugar) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890@gmail.com", "80", "1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890@gmail.com", 2, "DEFAULT IMAGE URL", "1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890@gmail.com", null, "-k37gv8dskdr4ljya05zif7fef6i03*suu699dom05zx4~zqk756qplwcrowq7bthg4pya+7o4be*s7yoj1uu0vo6d*l-ok5-gzifm46zhnbsychn7utt0zuxe8o7hny", 0, "clasve12345", 1]: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'txUsuEmail' at row 1" at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\dbal\lib\Doctrine\DBAL\DBALException.php line 91 {"exception":"[object] (Doctrine\\DBAL\\DBALException: An exception occurred while executing 'INSERT INTO lb_usuarios (txUsuEmail, txUsuTelefono, txUsuNombre, inUsuGenero, txUsuImagen, txUsuNomMostrar, feUsuNacimiento, txUsuValidacion, inUsuEstado, txUsuClave, inUsuLugar) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890@gmail.com\", \"80\", \"1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890@gmail.com\", 2, \"DEFAULT IMAGE URL\", \"1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890@gmail.com\", null, \"-k37gv8dskdr4ljya05zif7fef6i03*suu699dom05zx4~zqk756qplwcrowq7bthg4pya+7o4be*s7yoj1uu0vo6d*l-ok5-gzifm46zhnbsychn7utt0zuxe8o7hny\", 0, \"clasve12345\", 1]:\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'txUsuEmail' at row 1 at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\DBALException.php:91, PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'txUsuEmail' at row 1 at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Statement.php:165)"} []
[2015-10-20 06:44:04] request.INFO: Matched route "ex4read_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "ex4read_ingresarSistema") [] []
[2015-10-20 06:44:05] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Libreame\BackendBundle\Entity\LbSolicitados#insollibro' that was not configured to cascade persist operations for entity: Libreame\BackendBundle\Entity\LbLibros@000000002dcc84e1000000006fc3c3cf. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'Libreame\BackendBundle\Entity\LbLibros#__toString()' to get a clue." at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\orm\lib\Doctrine\ORM\ORMInvalidArgumentException.php line 91 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException: A new entity was found through the relationship 'Libreame\\BackendBundle\\Entity\\LbSolicitados#insollibro' that was not configured to cascade persist operations for entity: Libreame\\BackendBundle\\Entity\\LbLibros@000000002dcc84e1000000006fc3c3cf. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). If you cannot find out which entity causes the problem implement 'Libreame\\BackendBundle\\Entity\\LbLibros#__toString()' to get a clue. at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\ORMInvalidArgumentException.php:91)"} []
[2015-10-20 06:46:04] request.INFO: Matched route "ex4read_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "ex4read_ingresarSistema") [] []
[2015-10-20 06:46:04] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Libreame\BackendBundle\Entity\LbSolicitados#insollibro' that was not configured to cascade persist operations for entity: Libreame\BackendBundle\Entity\LbLibros@0000000004340f050000000000644b10. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'Libreame\BackendBundle\Entity\LbLibros#__toString()' to get a clue." at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\orm\lib\Doctrine\ORM\ORMInvalidArgumentException.php line 91 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException: A new entity was found through the relationship 'Libreame\\BackendBundle\\Entity\\LbSolicitados#insollibro' that was not configured to cascade persist operations for entity: Libreame\\BackendBundle\\Entity\\LbLibros@0000000004340f050000000000644b10. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). If you cannot find out which entity causes the problem implement 'Libreame\\BackendBundle\\Entity\\LbLibros#__toString()' to get a clue. at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\ORMInvalidArgumentException.php:91)"} []
[2015-10-20 06:46:43] request.INFO: Matched route "ex4read_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "ex4read_ingresarSistema") [] []
[2015-10-20 06:46:43] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Libreame\BackendBundle\Entity\LbSolicitados#insollibro' that was not configured to cascade persist operations for entity: Libreame\BackendBundle\Entity\LbLibros@00000000282378e60000000021b23cde. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'Libreame\BackendBundle\Entity\LbLibros#__toString()' to get a clue." at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\orm\lib\Doctrine\ORM\ORMInvalidArgumentException.php line 91 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException: A new entity was found through the relationship 'Libreame\\BackendBundle\\Entity\\LbSolicitados#insollibro' that was not configured to cascade persist operations for entity: Libreame\\BackendBundle\\Entity\\LbLibros@00000000282378e60000000021b23cde. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). If you cannot find out which entity causes the problem implement 'Libreame\\BackendBundle\\Entity\\LbLibros#__toString()' to get a clue. at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\ORMInvalidArgumentException.php:91)"} []
[2015-10-20 06:48:27] request.INFO: Matched route "ex4read_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "ex4read_ingresarSistema") [] []
[2015-10-20 06:48:27] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Libreame\BackendBundle\Entity\LbSolicitados#insollibro' that was not configured to cascade persist operations for entity: Libreame\BackendBundle\Entity\LbLibros@0000000012e9a73d000000002bca5312. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'Libreame\BackendBundle\Entity\LbLibros#__toString()' to get a clue." at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\orm\lib\Doctrine\ORM\ORMInvalidArgumentException.php line 91 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException: A new entity was found through the relationship 'Libreame\\BackendBundle\\Entity\\LbSolicitados#insollibro' that was not configured to cascade persist operations for entity: Libreame\\BackendBundle\\Entity\\LbLibros@0000000012e9a73d000000002bca5312. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). If you cannot find out which entity causes the problem implement 'Libreame\\BackendBundle\\Entity\\LbLibros#__toString()' to get a clue. at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\ORMInvalidArgumentException.php:91)"} []
[2015-10-20 06:50:49] request.INFO: Matched route "ex4read_ingresarSistema" (parameters: "_controller": "Libreame\BackendBundle\Controller\AccesoController::ingresarSistemaAction", "_format": "json", "_route": "ex4read_ingresarSistema") [] []
[2015-10-20 06:50:50] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Libreame\BackendBundle\Entity\LbSolicitados#insollibro' that was not configured to cascade persist operations for entity: Libreame\BackendBundle\Entity\LbLibros@0000000056e0b4c1000000003b00220b. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'Libreame\BackendBundle\Entity\LbLibros#__toString()' to get a clue." at C:\xampp\htdocs\Ex4ReadBE\vendor\doctrine\orm\lib\Doctrine\ORM\ORMInvalidArgumentException.php line 91 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException: A new entity was found through the relationship 'Libreame\\BackendBundle\\Entity\\LbSolicitados#insollibro' that was not configured to cascade persist operations for entity: Libreame\\BackendBundle\\Entity\\LbLibros@0000000056e0b4c1000000003b00220b. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). If you cannot find out which entity causes the problem implement 'Libreame\\BackendBundle\\Entity\\LbLibros#__toString()' to get a clue. at C:\\xampp\\htdocs\\Ex4ReadBE\\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\ORMInvalidArgumentException.php:91)"} []
